#!/bin/bash -e
# regenerate gitlab mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/home/gitlab/gitlab/config/database.yml
sed -i "s/password:\(.*\)/password: \"$PASSWORD\"/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=gitlab --pass="$PASSWORD"
