#!/bin/bash -e
# Create ssh keys for gitlab

. /etc/default/inithooks

echo "* Regenerating SSH cryptographic keys for gitlab user"

sudo -H -u gitlab ssh-keygen -q -N '' -t rsa -f /home/gitlab/.ssh/id_rsa
cp /home/gitlab/.ssh/id_rsa.pub /home/git/gitlab.pub
chmod 777 /home/git/gitlab.pub

echo "* Reconfiguring gitolite with new key"

sudo -u git -H sh -c "PATH=/home/git/bin:$PATH; gl-setup -q /home/git/gitlab.pub"
